// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solara.Data;

#nullable disable

namespace solara_backend.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20240819065042_CreateSeedData")]
    partial class CreateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Solara.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttackStat")
                        .HasColumnType("int");

                    b.Property<float>("BaseCritDamageStat")
                        .HasColumnType("float");

                    b.Property<float>("BaseCritRateStat")
                        .HasColumnType("float");

                    b.Property<float>("BaseEnergyRechargeStat")
                        .HasColumnType("float");

                    b.Property<int>("BaseSpeedStat")
                        .HasColumnType("int");

                    b.Property<string>("BasicAttack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FaceArt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullArt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("SpecialAttack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAttackStat = 100,
                            BaseCritDamageStat = 1.5f,
                            BaseCritRateStat = 0.1f,
                            BaseEnergyRechargeStat = 1f,
                            BaseSpeedStat = 20,
                            BasicAttack = "Sword Slash",
                            Description = "A laid-back wanderer drifting through Solara.",
                            Element = "Blue",
                            FaceArt = "art/margana-face.png",
                            FullArt = "art/margana.png",
                            Name = "Margana",
                            Price = 5000,
                            SpecialAttack = "Blazing Strike"
                        },
                        new
                        {
                            Id = 2,
                            BaseAttackStat = 80,
                            BaseCritDamageStat = 1.4f,
                            BaseCritRateStat = 0.12f,
                            BaseEnergyRechargeStat = 1.2f,
                            BaseSpeedStat = 15,
                            BasicAttack = "Water Blast",
                            Description = "A passionate artist known to get fired up.",
                            Element = "Magenta",
                            FaceArt = "art/a-face.png",
                            FullArt = "art/a.png",
                            Name = "Artemisia",
                            Price = 5000,
                            SpecialAttack = "Tsunami"
                        },
                        new
                        {
                            Id = 3,
                            BaseAttackStat = 80,
                            BaseCritDamageStat = 1.4f,
                            BaseCritRateStat = 0.12f,
                            BaseEnergyRechargeStat = 1.2f,
                            BaseSpeedStat = 15,
                            BasicAttack = "Water Blast",
                            Description = "A hardworking maid just trying her best.",
                            Element = "Magenta",
                            FaceArt = "art/b-face.png",
                            FullArt = "art/b.png",
                            Name = "Powder",
                            Price = 5000,
                            SpecialAttack = "Tsunami"
                        },
                        new
                        {
                            Id = 4,
                            BaseAttackStat = 80,
                            BaseCritDamageStat = 1.4f,
                            BaseCritRateStat = 0.12f,
                            BaseEnergyRechargeStat = 1.2f,
                            BaseSpeedStat = 15,
                            BasicAttack = "Water Blast",
                            Description = "A medical student currently enrolled at the University of Solara.",
                            Element = "Magenta",
                            FaceArt = "art/e-face.png",
                            FullArt = "art/e.png",
                            Name = "Ann",
                            Price = 5000,
                            SpecialAttack = "Tsunami"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
